version: "3.7"

networks:
  default:
    external:
      name: "homelab_base_default"

services:
  transmissionvpn:
    image: "haugene/transmission-openvpn"
    restart: "unless-stopped"
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - TRANSMISSION_UMASK=002
      - TRANSMISSION_RATIO_LIMIT=1.00
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/transmissionvpn/config:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.transmissionvpn.loadbalancer.server.port=9091"
      - "traefik.http.routers.transmissionvpn.rule=Host(`transmissionvpn.${DOMAIN_NAME}`)"
      - "traefik.http.routers.transmissionvpn.entrypoints=web-secure"
      - "traefik.http.routers.transmissionvpn.tls.certresolver=letsencrypt"
      - "traefik.http.routers.transmissionvpn.middlewares=authelia@docker"

