version: "3.7"

networks:
  default:
    external:
      name: "homelab_base_default"

services:
  radarr:
    image: "linuxserver/radarr"
    restart: "unless-stopped"
    environment:
      PUID: 1000
      GUID: 1000
      TZ: "${TIMEZONE}"
    volumes:
      - "./data/radarr:/config"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN_NAME}`)"
      - "traefik.http.routers.radarr.entrypoints=web-secure"
      - "traefik.http.routers.radarr.tls.certresolver=letsencrypt"
      - "traefik.http.routers.radarr.middlewares=authelia@docker"