version: "3.7"

networks:
  default:
    external:
      name: "homelab_base_default"

services:
  transmissionvpn:
    image: "haugene/transmission-openvpn"
    restart: "unless-stopped"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - PUID=1000
      - PGID=1000
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - NORDVPN_COUNTRY=US
      - NORDVPN_CATEGORY=P2P
      - NORDVPN_PROTOCOL=UDP
      - TRANSMISSION_UMASK=002
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_RATIO_LIMIT=0.5
      - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true
      - TRANSMISSION_IDLE_SEEDING_LIMIT=10
      - TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_DOWN=2000
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_UP=2000
      - TRANSMISSION_DOWNLOAD_DIR=/media/torrents/completed
      - TRANSMISSION_INCOMPLETE_DIR=/media/torrents/incomplete
      - TRANSMISSION_WATCH_DIR=/media/torrents/watch
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/transmissionvpn/config:/config
      - ${HOMELAB_DATA}:/data
      - ${MEDIA_DATA}:/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.transmissionvpn.loadbalancer.server.port=9091"
      - "traefik.http.routers.transmissionvpn.rule=Host(`transmission.${DOMAIN_NAME}`)"
      - "traefik.http.routers.transmissionvpn.entrypoints=web-secure"
      - "traefik.http.routers.transmissionvpn.tls.certresolver=letsencrypt"
      - "traefik.http.routers.transmissionvpn.middlewares=authelia@docker"

