version: "3.7"

networks:
  default:
    external:
      name: "homelab_base_default"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "${TIMEZONE}"
    volumes:
      - ${HOMELAB_DATA}/jellyfin:/config
      - ${MEDIA_DATA}/media:/data/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN_NAME}`)"
      - "traefik.http.routers.jellyfin.tls.certresolver=letsencrypt"
      - "traefik.http.routers.jellyfin.entrypoints=web-secure"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
