version: "3"

networks:
  default:
    name: "homelab_base_default"
    external: true

services:
  actual_server:
    image: actualbudget/actual-server:latest-alpine
    restart: unless-stopped
    volumes:
      - ./data/actual:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.actual.loadbalancer.server.port=5006"
      - "traefik.http.routers.actual.rule=Host(`budget.${DOMAIN_NAME}`)"
      - "traefik.http.routers.actual.entrypoints=web-secure"
      - "traefik.http.routers.actual.tls.certresolver=letsencrypt"
      - "traefik.http.routers.actual.middlewares=authelia@docker"
