networks:
  default:
    name: "homelab_base_default"
    external: true

services:
  plex:
    image: linuxserver/plex:latest
    environment:
      PUID: "${UID}"
      PGID: "${GID}"
      TZ: "${TIMEZONE}"
      # PLEX_CLAIM: claim-fGDmt63MMvCckyux5JkW
      ADVERTISE_IP: "https://plex.${DOMAIN_NAME}:443"
      VERSION: docker
    volumes:
      - ./data/plex/config:/config
      - ./data/plex/transcode:/transcode
      - ${MEDIA_DATA}:/data
    devices:
      - /dev/dri:/dev/dri
    hostname: "plex.${DOMAIN_NAME}"
    ports:
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32400:32400/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32400:32400/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
      - "traefik.http.routers.plex.rule=Host(`plex.${DOMAIN_NAME}`)"
      - "traefik.http.routers.plex.entrypoints=web-secure"
      - "traefik.http.routers.plex.tls.certresolver=letsencrypt"

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    restart: unless-stopped
    environment:
      PUID: "${UID}"
      PGID: "${GID}"
      TZ: "${TIMEZONE}"
    volumes:
      - ./data/tautulli/config:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.tautulli.loadbalancer.server.port=8181"
      - "traefik.http.routers.tautulli.rule=Host(`tautulli.${DOMAIN_NAME}`)"
      - "traefik.http.routers.tautulli.entrypoints=web-secure"
      - "traefik.http.routers.tautulli.tls.certresolver=letsencrypt"
      - "traefik.http.routers.tautulli.middlewares=authelia@docker"
