entryPoints:
  web:
    address: ":${HTTP_PORT}"
  web-secure:
    address: ":${HTTPS_PORT}"

api:
  dashboard: true
  insecure: true

providers:
  file:
    directory: "/config"
    watch: true
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: "homelab_base_default"
    watch: true
    exposedByDefault: false
#    constraints: Label(`com.docker.compose.project`,`homelab_base`)

certificatesResolvers:
  letsencrypt:
    acme:
      email: "${TLS_EMAIL}"
      storage: "/acme.json"
      httpChallenge:
        entryPoint: "web"

metrics:
  prometheus:
    entryPoint: "traefik"
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
